### ISSUE TITLE
Fix button to zero heading in teleop

### ISSUE THREAD

**Issue by ArthurAllshire** [thedropbears/pypowerup#22]
The current button to re-zero the gyro orientation in teleop is broken - it makes the robot turn by the amount the offset has changed by. We do try to reset the heading PID, but it does not appear to work. Suspect this is something to do with the navX not resetting immediately after we make the reset() call.

**Comment by auscompgeek** [comment]
There is a way to register a callback for yaw resets on the navX. Perhaps that is something we'll have to do.
